# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev

---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    #   连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    maximum-pool-size: 100
    #  一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
    idleTimeout: 600000
    # 连接只读数据库时配置为true， 保证安全
    isReadOnly: false
    #   等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
    connectionTimeout: 30000
    #  一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，
    #  参考MySQL wait_timeout参数（show variables like '%timeout%';）
    maxLifetime: 1800000
server:
  port: 8093

# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别
    com.grj.hellospringboot: debug
  # 指定输出日志的文件名，默认输出至当前项目目录下
  file: log/user/springboot.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n'

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
server:
  port: 8080